### ISSUE TITLE
a previous version  plz

### ISSUE THREAD

**Issue by tianrking** [s0danissa/3_phase_full_wave_rectifier#1]
CLD u plz upload a previous version  2018a or 2019a thx

**Comment by s0danissa** [comment]
Hi!

Are you getting error 146 while opening it? If yes simply rename the model file with underscores instead of dashes ("_" instead of "-") after download. Seems like while loading Simulink models they are changed to dashes which then prevents them from opening. (And error seems like the version difference is the problem but it's not). But if you are in need of the older version feel free to reply again here and I will load it :)
